name: Deploy Flask App

on:
  push:
    branches:
      - main  # Change this if you use a different branch

jobs:
  run-flask-app:
    runs-on: [self-hosted, ec2]  # This should match your runner's tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Start Flask app
        run: |
          nohup python3 app.py > output.log 2>&1 &
          sleep 5  # Wait for Flask to start

      - name: Test root endpoint
        run: |
          curl --fail http://127.0.0.1:5000

      - name: Test /get endpoint
        run: |
          curl --fail "http://127.0.0.1:5000/get?msg=hello"
