name: Deploy Flask App

on:
  push:
    branches:
      - main  # change if using a different branch

jobs:
  deploy:
    runs-on: [self-hosted, ec2]  # must match your runner tag

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Kill previous Flask process (if any)
        run: |
          pkill -f "python3 app.py" || true

      - name: Start Flask app
        run: |
          nohup python3 app.py > flask.log 2>&1 &

      - name: Wait for server to start
        run: sleep 5

      - name: Test Flask app is running
        run: |
          curl http://127.0.0.1:5000
