name: Flask App CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask app in background
        run: |
          nohup python app.py &
          sleep 5  # Give the server time to start

      - name: Test Flask endpoint
        run: |
          curl -f http://127.0.0.1:5000/
          curl -f "http://127.0.0.1:5000/api/echo?msg=hello"

  # Optional: Deploy job (example placeholder)
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Echo deploy step
        run: echo "You can configure your deployment here (Heroku, AWS, etc.)"
