name: Hello World Flask CI

on:
  push:
    branches: [main]

jobs:
  run-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Flask app in background
        run: |
          nohup python app.py > flask.log 2>&1 &
          sleep 5  # give it time to start

      - name: Test Flask root endpoint
        run: |
          curl -f http://127.0.0.1:5000/
