name: Hello World Flask CI

on:
  push:
    branches: [main]

jobs:
  run-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Flask app in background
        run: |
          nohup python app.py &
          sleep 5  # Let Flask boot

      - name: Test Flask endpoint with curl
        run: |
          curl -f http://127.0.0.1:5000/
